In [1]:
from __future__ import print_function
import torch

In [2]:
# Tensors

In [3]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  3.0297e+32,  2.7224e+20],
        [ 7.7782e+31,  4.7429e+30,  1.3818e+31],
        [ 1.7225e+22,  1.4602e-19,  1.8617e+25],
        [ 1.1835e+22,  4.3066e+21,  6.3828e+28]])


In [4]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.1909, 0.9081, 0.0617],
        [0.4454, 0.9349, 0.1353],
        [0.8201, 0.8674, 0.3757],
        [0.5450, 0.3785, 0.3264],
        [0.7913, 0.4354, 0.2440]])


In [5]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# or create a tensor bases on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.
x = x.new_ones(5, 3, dtype=torch.double)    # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.rand_like(x, dtype=torch.float)   # override dtype!
print(x)

tensor([[0.7572, 0.7105, 0.5106],
        [0.1659, 0.0942, 0.3892],
        [0.0237, 0.2645, 0.7006],
        [0.5960, 0.5713, 0.4800],
        [0.9588, 0.3914, 0.8073]])


In [8]:
# Get its size:
print(x.size())

torch.Size([5, 3])


In [9]:
# Operations

In [10]:
# Addition: syntax 1
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2964, 0.7176, 1.0137],
        [0.7568, 0.1203, 0.6661],
        [0.8953, 1.0710, 1.1012],
        [1.1796, 1.5353, 1.1148],
        [1.5554, 1.3471, 1.0146]])
