In [1]:
from __future__ import print_function
import torch

In [2]:
# Tensors

In [3]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  5.6052e-45,  0.0000e+00],
        [ 8.2498e-34,  1.4013e-45, -1.4393e+22],
        [ 4.5853e-41,  0.0000e+00,  0.0000e+00],
        [ 4.4620e-11, -4.6577e-10,  4.4609e-11]])


In [4]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.6661, 0.1863, 0.7925],
        [0.7096, 0.9026, 0.5634],
        [0.2822, 0.2051, 0.5063],
        [0.1157, 0.3504, 0.9759],
        [0.5185, 0.5085, 0.0179]])


In [5]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.
x = x.new_ones(5, 3, dtype=torch.double)    # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.rand_like(x, dtype=torch.float)   # override dtype!
print(x)

tensor([[1.2239e-01, 6.5364e-01, 7.8861e-01],
        [8.4257e-01, 9.5634e-01, 3.2474e-01],
        [6.9625e-02, 3.0557e-01, 9.2113e-01],
        [1.8900e-02, 9.9752e-01, 6.4405e-01],
        [6.0775e-01, 7.2360e-05, 9.3798e-01]])


In [8]:
# Get its size:
print(x.size())

torch.Size([5, 3])


In [9]:
# Operations
# There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [10]:
# Addition: syntax 1
y = torch.rand(5, 3)
print(x + y)

tensor([[0.1594, 1.1615, 0.8987],
        [1.0675, 1.0992, 0.4737],
        [0.5131, 1.1793, 1.3317],
        [0.6511, 1.5840, 1.0235],
        [1.0074, 0.1483, 0.9826]])


In [11]:
# Addition syntax 2

In [12]:
print(torch.add(x, y))

tensor([[0.1594, 1.1615, 0.8987],
        [1.0675, 1.0992, 0.4737],
        [0.5131, 1.1793, 1.3317],
        [0.6511, 1.5840, 1.0235],
        [1.0074, 0.1483, 0.9826]])


In [13]:
# Addition: providing an output tensor as argument

In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.1594, 1.1615, 0.8987],
        [1.0675, 1.0992, 0.4737],
        [0.5131, 1.1793, 1.3317],
        [0.6511, 1.5840, 1.0235],
        [1.0074, 0.1483, 0.9826]])


In [15]:
# Addition: in-place

In [16]:
y.add_(x)
print(y)

tensor([[0.1594, 1.1615, 0.8987],
        [1.0675, 1.0992, 0.4737],
        [0.5131, 1.1793, 1.3317],
        [0.6511, 1.5840, 1.0235],
        [1.0074, 0.1483, 0.9826]])


In [17]:
# NOTE
# Any operation that mutates a tensor in-place is post-fixed wiath an '_'. For eample 'x.copy_(y)', 'x.t_()', will change 'x'.

In [18]:
# You can use standard NumPy-like indexing with all bells and whistles!

In [19]:
print(x[:, 1])

tensor([6.5364e-01, 9.5634e-01, 3.0557e-01, 9.9752e-01, 7.2360e-05])


In [20]:
# Rezising: if you want to resize/reshape tensor, you can use 'torch.view'

In [21]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is infereded from other dimensiones
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
# If you have one element te3nsor, use '.item()' to get the value as a Python number

In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7432])
0.7432321310043335


In [24]:
# NumPy Bridge
# Converting a Torch Tensor to a NumPy array and vice versar is a breeze.
# The Torch Tensor and NumPy will share thir underlaying memory locations (if the Torch Tensor is on CPU), and changing
# one will change the other.

In [25]:
# Converting a Torch Tensor to a NumPy Array

In [26]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [27]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [28]:
# See how the numpy array changes in value

In [29]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [30]:
# Converting NumPy Array to Torch Tensor
# See how changing the np array changed the Torch Tensor automatically

In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
# All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [33]:
# CUDA Tensors
# Tensors can be moved onto any device using the '.to' method.

In [34]:
# let us run this cell only if CUDA is avaliable
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")              # a CUDA device object
    y = torch.ones_like(x, device=device)      # directly create a tensor on GPU
    x = x.to(device)                           # or just use string ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))           # ``.to`` can also change dtype together!