In [16]:
# Autograd: Automatic Differentiation

In [17]:
import torch

In [3]:
# Create a tensor and set ``requires_grad=True`` to track computation on it

In [5]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
# Do a tensor operation:

In [7]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
# ``y`` was created as a result of an operation, so it has a ``grad_fn``.

In [10]:
print(y.grad_fn)

In [11]:
# Do more operations on ``y``

In [13]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [14]:
# ``.requires_grad_(...)`` changes and existing Tensor's ``requires_grad`` flag in-place. The input flag defaults to ``False`` if not given.

In [18]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [19]:
# Gradients